---

- name: sync node install including node_modules
  become: no
  synchronize:
    src: ~/project/backend/
    dest: /home/ubuntu/backend
    checksum: no
    archive: no
    recursive: yes

- name: start pm2 for dist/main.js
  become: no
  shell: pm2 start main.js
  args:
    chdir: /home/ubuntu/backend/dist